config/routes.rb
Rails.application.routes.draw do
  get 'chirps/index'

  get 'chirps/new'

  get 'chirps/edit'

  get 'chirps/show'

  resources :chirps

  scope ':author', as: 'author' do
    resources :chirps, except: ['create', 'update', 'destroy']
  end
  get 'home/index'
  root to: 'home#index'

end

app/models/chirp.rb
class Chirp < ActiveRecord::Base

has_attached_file :pic, default_url: ""
validates_attachment :pic, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chirps_controller.rb
class ChirpsController < ApplicationController
  def index
    @chirps = Chirp.where(params.permit(:author))
  end

  def new
    @chirp = Chirp.new(params.permit(:author))
  end

  def edit
    @chirp = Chirp.find_by(params.permit(:author, :id))
  end

  def show
    @chirp = Chirp.find_by(params.permit(:author, :id))
  end

  def update
    @chirp = Chirp.find(params[:id])
    if @chirp.update(params[:chirp].permit(:author, :body, :pic))
      redirect_to chirp_path(@chirp)
    else
      render 'edit'
    end
  end

  def destroy
    Chirp.find(params[:id]).destroy
    redirect_to chirps_path
  end


  def create
    @chirp = Chirp.new(params[:chirp].permit(:author, :body, :pic))
    if @chirp.save
      redirect_to chirp_path(@chirp)
    else
      render 'new'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chirps_helper.rb
module ChirpsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/chirps/edit.html.erb
<div class = "container">
<h1>Edit this Chirp</h1>

<%= form_for @chirp do |f| %>

<div>
<%= f.label :author %>
<%= f.text_field :author %>
</div>

<div>
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>

<div>
  <%= f.label :pic %>
  <%= f.file_field :pic %>

</div>

<div>
  <%= f.submit 'Save' %>
</div>

<% end %>
</div>

app/views/chirps/index.html.erb
<div class = "container">
<h1>Chirps</h1>

<%= link_to "Make a new Chirp", new_chirp_path %>
<hr>
<% @chirps.each do |chirp| %>

<p><%= chirp.body %></p>
<%= image_tag chirp.pic.url, width: '100' %>
<p>
  - <i><%= link_to chirp.author, author_chirps_path(chirp.author) %></i>
</p>

<%= link_to "Read more", chirp_path(chirp) %>

<% end -%>
</div>

app/views/chirps/new.html.erb
<div class="container"> 
<h1>Make a Chirp</h1>

<%= form_for @chirp do |f| %>
<div>
<%= f.label :author %>
<%= f.text_field :author %>
</div>

<div>
  <%= f.label :body %>
  <%= f.text_area :body %>

</div>

<div>
  <%= f.label :pic %>
  <%= f.file_field :pic %>

</div>

<div>
  <%= f.submit 'Chirp!' %>

</div>
<% end %>
</div>

app/views/chirps/show.html.erb
<div class="container"> 
<h1>Chirp</h1>
<p><%= @chirp.body %></p>
<%= image_tag @chirp.pic.url, width: '100' %>
<p>
  -<i><%= @chirp.author %></i>
</p>
<%= link_to "Edit this Chirp", edit_chirp_path(@chirp) %>
<br>
<%= link_to "Delete this Chirp", chirp_path(@chirp), method: 'delete' %>
<br>
<%= link_to "See All Chirps", chirps_path %>
</div>

app/views/home/index.html.erb
<h1>Chirper</h1>
<p>This is Chirper, a fun way to post short messages on the web!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chirper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>